### PR TITLE
Build August 18th.

### PR DESCRIPTION
**Pull request by aw-asana**

### CODE REVIEW

**Comment by jv-asana** [comment]
What's output.ts?

**Comment by jv-asana** [comment]
also package.json and package-lock.json is included was that intentional?

**Comment by aw-asana** [comment]
Removed and `.gitignore` updated 👍

**Comment by jv-asana** [comment]
Can you remove `.DS_Store` and `output.ts`

**Review by jv-asana — APPROVED** [review]
LGTM. There are a lot of changes for the OAS file that the Git diff can't view. Taking a quick look at the raw file it looks ok.

**Pull request merged**
